// Generated by scripts/build-plugin.mjs. Do not edit directly.
// Figma loads this single sandbox artifact through plugin/manifest.json.

// Source: plugin/shared/data.js
function createPluginDataHelpers() {
  function cloneData(value) {
    if (value === undefined) return undefined;
    return JSON.parse(JSON.stringify(value));
  }

  function canonicalJson(value) {
    function normalize(input) {
      if (Array.isArray(input)) return input.map(normalize);
      if (input && typeof input === "object") {
        const output = {};
        for (const key of Object.keys(input).sort()) {
          output[key] = normalize(input[key]);
        }
        return output;
      }
      return input;
    }
    return JSON.stringify(normalize(value));
  }

  return { cloneData, canonicalJson };
}

// Source: plugin/runtime/errors.js
function createPluginErrors() {
  /**
   * @param {string} code
   * @param {string} message
   * @param {boolean} [retryable]
   * @param {Record<string, unknown>} [details]
   * @returns {never}
   */
  function fail(code, message, retryable = false, details) {
    const error = /** @type {Error & { bridge?: Record<string, unknown> }} */ (
      new Error(message)
    );
    error.bridge = {
      code,
      message,
      retryable,
      ...(details ? { details } : {}),
    };
    throw error;
  }

  function assertNodeIds(value) {
    if (
      !Array.isArray(value) ||
      value.length === 0 ||
      value.some((id) => typeof id !== "string" || !id)
    ) {
      fail(
        "INVALID_ARGUMENT",
        "nodeIds must contain at least one explicit node ID.",
      );
    }
  }

  return { fail, assertNodeIds };
}

// Source: plugin/runtime/metrics.js
function createPluginMetrics() {
  let activeCommandMetrics = null;

  function start() {
    activeCommandMetrics = { sceneTraversalNodeCount: 0 };
  }

  function countSceneTraversal(count = 1) {
    if (activeCommandMetrics) {
      activeCommandMetrics.sceneTraversalNodeCount += count;
    }
  }

  function sceneTraversalNodeCount() {
    return activeCommandMetrics?.sceneTraversalNodeCount ?? 0;
  }

  function finish() {
    activeCommandMetrics = null;
  }

  return { start, countSceneTraversal, sceneTraversalNodeCount, finish };
}

// Source: plugin/runtime/revision.js
function createPluginRevisionRuntime({ cloneData }) {
  let revision = 1;
  const changes = [];
  const revisionReadCache = new Map();
  const pendingInternalChanges = [];
  const internalChangeWindowMs = 2000;

  function current() {
    return revision;
  }

  async function revisionCached(key, loader) {
    const cacheKey = `${revision}:${key}`;
    if (revisionReadCache.has(cacheKey)) {
      return cloneData(revisionReadCache.get(cacheKey));
    }
    const value = await loader();
    revisionReadCache.set(cacheKey, cloneData(value));
    return value;
  }

  function recordChange(action, nodeIds) {
    revision += 1;
    revisionReadCache.clear();
    pendingInternalChanges.push({
      timestamp: Date.now(),
      nodeIds: new Set(nodeIds),
    });
    changes.push({
      revision: String(revision),
      action,
      nodeIds: [...nodeIds],
      timestamp: new Date().toISOString(),
    });
    if (changes.length > 500) changes.splice(0, changes.length - 500);
  }

  function recordExternalChange(event) {
    const cutoff = Date.now() - internalChangeWindowMs;
    while (pendingInternalChanges[0]?.timestamp < cutoff) {
      pendingInternalChanges.shift();
    }
    const documentChanges = event?.documentChanges;
    if (!Array.isArray(documentChanges) || documentChanges.length === 0) {
      revision += 1;
      revisionReadCache.clear();
      return;
    }
    const matchedIndexes = new Set();
    const claimedIdsByIndex = new Map();
    let isInternalBatch = true;
    for (const change of documentChanges) {
      if (change.origin !== "LOCAL") {
        isInternalBatch = false;
        continue;
      }
      const matchingIndex = pendingInternalChanges.findIndex(
        (pending, index) =>
          pending.nodeIds.has(change.id) &&
          !claimedIdsByIndex.get(index)?.has(change.id),
      );
      if (matchingIndex < 0) {
        isInternalBatch = false;
        continue;
      }
      const claimedIds = claimedIdsByIndex.get(matchingIndex) ?? new Set();
      claimedIds.add(change.id);
      claimedIdsByIndex.set(matchingIndex, claimedIds);
      matchedIndexes.add(matchingIndex);
    }
    for (const index of [...matchedIndexes].sort((a, b) => b - a)) {
      pendingInternalChanges.splice(index, 1);
    }
    if (isInternalBatch) return;
    revision += 1;
    revisionReadCache.clear();
  }

  function getChanges() {
    return cloneData(changes);
  }

  return {
    current,
    revisionCached,
    recordChange,
    recordExternalChange,
    getChanges,
  };
}

// Source: plugin/runtime/identity.js
function createPluginIdentity({ figma, revision }) {
  return function fileIdentity() {
    return {
      key: figma.fileKey || `local:${figma.root.id}`,
      name: figma.root.name || "Untitled Figma file",
      revision: String(revision.current()),
    };
  };
}

// Source: plugin/runtime/idempotency.js
function createPluginIdempotency({ canonicalJson, cloneData, fail }) {
  const results = new Map();

  function prepare(fileKey, command) {
    if (!command.idempotencyKey) return undefined;
    const cacheKey = `${fileKey}\u0000${command.idempotencyKey}`;
    const fingerprint = canonicalJson({
      method: command.method,
      params: command.params || {},
    });
    const existing = results.get(cacheKey);
    if (existing) {
      if (existing.fingerprint !== fingerprint) {
        fail(
          "INVALID_ARGUMENT",
          `Idempotency key ${command.idempotencyKey} was reused with a different payload.`,
        );
      }
      return {
        cacheKey,
        fingerprint,
        replayed: true,
        data: cloneData(existing.data),
      };
    }
    return { cacheKey, fingerprint, replayed: false };
  }

  function store(prepared, data) {
    if (!prepared) return;
    results.set(prepared.cacheKey, {
      fingerprint: prepared.fingerprint,
      data: cloneData(data),
    });
    if (results.size > 1_000) {
      const oldest = results.keys().next().value;
      if (oldest) results.delete(oldest);
    }
  }

  return { prepare, store };
}

// Source: plugin/shared/node.js
function createPluginNodeHelpers({ figma, fail, countSceneTraversal }) {
  async function nodeById(id) {
    const node = await figma.getNodeByIdAsync(id);
    if (!node)
      fail("NODE_NOT_FOUND", `Figma node ${id} was not found.`, false, {
        nodeId: id,
      });
    return node;
  }

  /**
   * @param {BaseNode} node
   * @returns {node is BaseNode & ChildrenMixin}
   */
  function hasChildren(node) {
    return "children" in node && Array.isArray(node.children);
  }

  function parentId(node) {
    return node.parent && node.parent.type !== "DOCUMENT"
      ? node.parent.id
      : node.parent?.id;
  }

  function toPluginConstraints(constraints) {
    const horizontal = {
      LEFT: "MIN",
      RIGHT: "MAX",
      CENTER: "CENTER",
      LEFT_RIGHT: "STRETCH",
      SCALE: "SCALE",
    };
    const vertical = {
      TOP: "MIN",
      BOTTOM: "MAX",
      CENTER: "CENTER",
      TOP_BOTTOM: "STRETCH",
      SCALE: "SCALE",
    };
    return {
      horizontal: horizontal[constraints.horizontal],
      vertical: vertical[constraints.vertical],
    };
  }

  function fromPluginConstraints(constraints) {
    const horizontal = {
      MIN: "LEFT",
      MAX: "RIGHT",
      CENTER: "CENTER",
      STRETCH: "LEFT_RIGHT",
      SCALE: "SCALE",
    };
    const vertical = {
      MIN: "TOP",
      MAX: "BOTTOM",
      CENTER: "CENTER",
      STRETCH: "TOP_BOTTOM",
      SCALE: "SCALE",
    };
    return {
      horizontal: horizontal[constraints.horizontal] ?? constraints.horizontal,
      vertical: vertical[constraints.vertical] ?? constraints.vertical,
    };
  }

  function normalizeVisual(value) {
    if (typeof value === "number")
      return Math.round(value * 1_000_000) / 1_000_000;
    if (Array.isArray(value)) return value.map(normalizeVisual);
    if (value && typeof value === "object")
      return Object.fromEntries(
        Object.entries(value).map(([key, item]) => [
          key,
          normalizeVisual(item),
        ]),
      );
    return value;
  }

  function mixedValue(value) {
    return value === figma.mixed ? { mixed: true } : normalizeVisual(value);
  }

  function serializePaint(paint) {
    if (
      paint.type !== "SOLID" &&
      ![
        "GRADIENT_LINEAR",
        "GRADIENT_RADIAL",
        "GRADIENT_ANGULAR",
        "GRADIENT_DIAMOND",
      ].includes(paint.type)
    )
      return normalizeVisual(paint);
    const output = { type: paint.type };
    if (paint.type === "SOLID") output.color = normalizeVisual(paint.color);
    else {
      output.gradientTransform = normalizeVisual(paint.gradientTransform);
      output.gradientStops = normalizeVisual(paint.gradientStops).map(
        (stop) => ({
          position: stop.position,
          color: stop.color,
        }),
      );
    }
    if (paint.opacity !== undefined && paint.opacity !== 1)
      output.opacity = normalizeVisual(paint.opacity);
    if (paint.visible === false) output.visible = false;
    if (paint.blendMode && paint.blendMode !== "NORMAL")
      output.blendMode = paint.blendMode;
    return output;
  }

  function serializePaints(paints) {
    if (paints === figma.mixed) return { mixed: true };
    return paints.map(serializePaint);
  }

  function serializeEffects(effects) {
    if (effects === figma.mixed) return { mixed: true };
    return effects.map((effect) => {
      if (effect.type === "DROP_SHADOW" || effect.type === "INNER_SHADOW")
        return {
          type: effect.type,
          color: normalizeVisual(effect.color),
          offset: normalizeVisual(effect.offset),
          radius: normalizeVisual(effect.radius),
          ...(effect.spread !== undefined
            ? { spread: normalizeVisual(effect.spread) }
            : {}),
          visible: effect.visible,
          blendMode: effect.blendMode,
        };
      if (effect.type === "LAYER_BLUR" || effect.type === "BACKGROUND_BLUR")
        return {
          type: effect.type,
          radius: normalizeVisual(effect.radius),
          visible: effect.visible,
          blurType: effect.blurType,
        };
      return normalizeVisual(effect);
    });
  }

  const typographyKeys = [
    "fontName",
    "fontSize",
    "lineHeight",
    "letterSpacing",
    "textAlignHorizontal",
    "textAlignVertical",
  ];

  function hasTextMutation(props) {
    return (
      props?.text !== undefined ||
      typographyKeys.some((key) => props?.[key] !== undefined)
    );
  }

  async function loadFontsForTextMutation(node, props) {
    if (!hasTextMutation(props)) return;
    if (node.type !== "TEXT")
      fail("INVALID_ARGUMENT", `Node ${node.id} is not a text node.`);
    if (
      props.text !== undefined &&
      node.fontName === figma.mixed &&
      props.fontName === undefined
    )
      fail(
        "INVALID_ARGUMENT",
        `Text node ${node.id} uses mixed fonts; provide fontName to replace its text uniformly.`,
      );

    let fonts;
    if (props.fontName !== undefined) {
      fonts = [props.fontName];
    } else if (node.fontName !== figma.mixed) {
      fonts = [node.fontName];
    } else if (typeof node.getRangeAllFontNames === "function") {
      fonts = node.getRangeAllFontNames(0, node.characters.length);
    } else {
      fail("INVALID_ARGUMENT", `Text node ${node.id} uses mixed fonts.`);
    }

    const uniqueFonts = new Map(
      fonts.map((font) => [`${font.family}\u0000${font.style}`, font]),
    );
    await Promise.all(
      [...uniqueFonts.values()].map((font) => figma.loadFontAsync(font)),
    );
  }

  function componentDefinitions(node) {
    try {
      return node.componentPropertyDefinitions || {};
    } catch {
      if (node.type === "COMPONENT" && node.parent?.type === "COMPONENT_SET")
        return node.parent.componentPropertyDefinitions || {};
      return {};
    }
  }

  async function serializeNode(node, deep = false, countTraversal = true) {
    if (countTraversal) countSceneTraversal();
    const output = { id: node.id, type: node.type, name: node.name };
    const parent = parentId(node);
    if (parent) output.parentId = parent;
    for (const key of ["x", "y", "width", "height", "visible", "locked"]) {
      if (key in node && typeof node[key] !== "symbol") output[key] = node[key];
    }
    if (node.type === "TEXT" && node.characters !== figma.mixed)
      output.text = node.characters;
    if (node.type === "TEXT") {
      for (const key of typographyKeys) {
        if (node[key] !== undefined && node[key] !== figma.mixed)
          output[key] = node[key];
      }
    }
    if ("fills" in node) output.fills = serializePaints(node.fills);
    if ("strokes" in node) output.strokes = serializePaints(node.strokes);
    for (const key of ["opacity", "cornerRadius", "blendMode"]) {
      if (key in node && node[key] !== undefined)
        output[key] = mixedValue(node[key]);
    }
    if ("effects" in node && node.effects !== undefined)
      output.effects = serializeEffects(node.effects);
    if (
      "topLeftRadius" in node &&
      "topRightRadius" in node &&
      "bottomRightRadius" in node &&
      "bottomLeftRadius" in node
    ) {
      output.cornerRadii = {
        topLeft: normalizeVisual(node.topLeftRadius),
        topRight: normalizeVisual(node.topRightRadius),
        bottomRight: normalizeVisual(node.bottomRightRadius),
        bottomLeft: normalizeVisual(node.bottomLeftRadius),
      };
    }
    if (node.type === "COMPONENT" || node.type === "COMPONENT_SET") {
      output.componentKey = node.key;
      output.componentSource = node.remote ? "library" : "local";
      output.description = node.description;
      output.componentProperties = Object.fromEntries(
        Object.entries(componentDefinitions(node)).map(([name, definition]) => [
          name,
          {
            type: definition.type,
            defaultValue: definition.defaultValue,
            ...(definition.variantOptions
              ? { options: [...definition.variantOptions] }
              : definition.preferredValues
                ? {
                    options: definition.preferredValues.map(
                      (value) => value.key,
                    ),
                  }
                : {}),
            ...(definition.description !== undefined
              ? { description: definition.description }
              : {}),
            ...(definition.slotSettings
              ? { slotSettings: { ...definition.slotSettings } }
              : {}),
          },
        ]),
      );
    }
    if (node.type === "INSTANCE") {
      const mainComponent = await node.getMainComponentAsync();
      output.mainComponentId = mainComponent?.id;
      output.mainComponentKey = mainComponent?.key;
      output.instanceProperties = Object.fromEntries(
        Object.entries(node.componentProperties || {}).map(([key, value]) => [
          key,
          value.value,
        ]),
      );
    }
    if ("boundVariables" in node) {
      output.boundVariables = Object.fromEntries(
        Object.entries(node.boundVariables || {}).map(([key, value]) => [
          key,
          value.id,
        ]),
      );
    }
    for (const key of [
      "layoutMode",
      "itemSpacing",
      "paddingTop",
      "paddingRight",
      "paddingBottom",
      "paddingLeft",
      "primaryAxisAlignItems",
      "counterAxisAlignItems",
      "layoutWrap",
      "primaryAxisSizingMode",
      "counterAxisSizingMode",
      "layoutSizingHorizontal",
      "layoutSizingVertical",
      "minWidth",
      "maxWidth",
      "minHeight",
      "maxHeight",
      "layoutAlign",
      "layoutPositioning",
    ]) {
      if (
        key in node &&
        node[key] !== undefined &&
        typeof node[key] !== "symbol"
      )
        output[key] = node[key];
    }
    if ("constraints" in node && node.constraints !== undefined)
      output.constraints = fromPluginConstraints(node.constraints);
    if (deep && hasChildren(node))
      output.children = await Promise.all(
        node.children.map((child) => serializeNode(child, true)),
      );
    return output;
  }

  async function applyProps(node, props) {
    if (!props) return;
    if (props.name !== undefined) node.name = props.name;
    for (const key of ["x", "y", "visible", "locked"]) {
      if (props[key] !== undefined && key in node) node[key] = props[key];
    }
    if (
      (props.width !== undefined || props.height !== undefined) &&
      "resize" in node
    ) {
      node.resize(props.width ?? node.width, props.height ?? node.height);
    }
    if (hasTextMutation(props)) {
      if (props.fontName !== undefined) node.fontName = props.fontName;
      if (props.text !== undefined) node.characters = props.text;
      for (const key of typographyKeys) {
        if (key !== "fontName" && props[key] !== undefined)
          node[key] = props[key];
      }
    }
    if (props.fills !== undefined && "fills" in node) node.fills = props.fills;
    if (props.strokes !== undefined && "strokes" in node)
      node.strokes = props.strokes;
    for (const key of ["opacity", "cornerRadius", "effects", "blendMode"]) {
      if (props[key] !== undefined && key in node) node[key] = props[key];
    }
    if (props.constraints !== undefined && "constraints" in node)
      node.constraints = toPluginConstraints(props.constraints);
  }

  const visualMutationKeys = new Set([
    "fills",
    "strokes",
    "opacity",
    "cornerRadius",
    "effects",
    "blendMode",
    "constraints",
  ]);

  async function validateProps(node, props) {
    if (!props) return;
    for (const key of Object.keys(props)) {
      const property = key === "text" ? "characters" : key;
      if (
        visualMutationKeys.has(key) &&
        property in node &&
        node[property] === figma.mixed
      )
        fail(
          "INVALID_ARGUMENT",
          `Node ${node.id} has mixed ${property}; whole-node mutation is unsupported.`,
        );
    }
    if (
      (props.width !== undefined || props.height !== undefined) &&
      !("resize" in node)
    )
      fail("INVALID_ARGUMENT", `Node ${node.id} cannot be resized.`);
    await loadFontsForTextMutation(node, props);
    if (props.fills !== undefined && !("fills" in node))
      fail("INVALID_ARGUMENT", `Node ${node.id} does not support fills.`);
    if (props.strokes !== undefined && !("strokes" in node))
      fail("INVALID_ARGUMENT", `Node ${node.id} does not support strokes.`);
    for (const key of [
      "opacity",
      "cornerRadius",
      "effects",
      "blendMode",
      "constraints",
    ]) {
      if (props[key] !== undefined && !(key in node))
        fail("INVALID_ARGUMENT", `Node ${node.id} does not support ${key}.`);
    }
  }

  function createByType(type) {
    switch (type) {
      case "FRAME":
        return figma.createFrame();
      case "GROUP":
        return fail(
          "UNSUPPORTED_BY_BRIDGE",
          "GROUP creation requires existing child nodes.",
        );
      case "RECTANGLE":
        return figma.createRectangle();
      case "ELLIPSE":
        return figma.createEllipse();
      case "LINE":
        return figma.createLine();
      case "TEXT":
        return figma.createText();
      case "COMPONENT":
        return figma.createComponent();
      default:
        fail(
          "UNSUPPORTED_BY_BRIDGE",
          `Desktop Plugin cannot create ${type} nodes.`,
        );
    }
  }
  return {
    nodeById,
    hasChildren,
    parentId,
    toPluginConstraints,
    fromPluginConstraints,
    serializeNode,
    serializePaints,
    applyProps,
    validateProps,
    createByType,
  };
}

// Source: plugin/domains/core-node.js
function createCoreNodeDomain({
  figma,
  fail,
  assertNodeIds,
  cloneData,
  revisionCached,
  recordChange,
  getChanges,
  countSceneTraversal,
  nodeById,
  hasChildren,
  serializeNode,
  serializePaints,
  applyProps,
  validateProps,
  createByType,
}) {
  const exportFormats = ["PNG", "JPG", "SVG", "PDF"];
  const exportMimeTypes = {
    PNG: "image/png",
    JPG: "image/jpeg",
    SVG: "image/svg+xml",
    PDF: "application/pdf",
  };
  const maxExportBytes = 650_000;
  const maxTextRangeCharacters = 10_000;

  async function queryNodes(input) {
    const maxDepth = input.maxDepth ?? 8;
    const limit = input.limit ?? 50;
    if (!Number.isInteger(maxDepth) || maxDepth < 0 || maxDepth > 20)
      fail(
        "INVALID_ARGUMENT",
        "node.query maxDepth must be an integer from 0 to 20.",
      );
    if (!Number.isInteger(limit) || limit < 1 || limit > 100)
      fail(
        "INVALID_ARGUMENT",
        "node.query limit must be an integer from 1 to 100.",
      );
    if (
      input.name === undefined &&
      input.nodeType === undefined &&
      input.path === undefined
    )
      fail("INVALID_ARGUMENT", "node.query requires name, nodeType, or path.");
    if (
      input.path !== undefined &&
      (!Array.isArray(input.path) ||
        input.path.length < 1 ||
        input.path.length > 20 ||
        input.path.some((segment) => typeof segment !== "string" || !segment))
    )
      fail(
        "INVALID_ARGUMENT",
        "node.query path must contain 1 to 20 non-empty segments.",
      );

    const root = input.rootId ? await nodeById(input.rootId) : figma.root;
    if (root.type === "DOCUMENT") await figma.loadAllPagesAsync();
    const caseSensitive = input.caseSensitive ?? true;
    const nameMatch = input.nameMatch ?? "exact";
    const normalize = (value) =>
      caseSensitive ? value : value.toLocaleLowerCase("en-US");
    const expectedName =
      input.name === undefined ? undefined : normalize(input.name);
    const samePath = (actual) =>
      input.path === undefined ||
      (actual.length === input.path.length &&
        actual.every(
          (segment, index) =>
            normalize(segment) === normalize(input.path[index]),
        ));
    const matches = [];
    let truncated = false;

    const visit = async (node, path, depth) => {
      if (depth > maxDepth) return false;
      countSceneTraversal();
      const actualName = normalize(node.name);
      const matchesName =
        expectedName === undefined ||
        (nameMatch === "contains"
          ? actualName.includes(expectedName)
          : actualName === expectedName);
      if (
        matchesName &&
        (input.nodeType === undefined || node.type === input.nodeType) &&
        samePath(path)
      ) {
        if (matches.length === limit) {
          truncated = true;
          return true;
        }
        matches.push({
          node: await serializeNode(node, false, false),
          path: [...path],
        });
      }
      if (depth === maxDepth || !hasChildren(node)) return false;
      for (const child of node.children) {
        if (await visit(child, [...path, child.name], depth + 1)) return true;
      }
      return false;
    };

    if (hasChildren(root)) {
      for (const child of root.children) {
        if (await visit(child, [child.name], 1)) break;
      }
    }
    return { matches, limit, truncated };
  }

  function capturePatchState(node, patch) {
    const state = { unrestorableMixed: [] };
    for (const key of Object.keys(patch)) {
      if (key === "width" || key === "height") continue;
      const property = key === "text" ? "characters" : key;
      if (!(property in node)) continue;
      if (typeof node[property] === "symbol") {
        state.unrestorableMixed.push(property);
        continue;
      }
      state[property] = cloneData(node[property]);
    }
    if (
      (patch.width !== undefined || patch.height !== undefined) &&
      "resize" in node
    )
      state.size = { width: node.width, height: node.height };
    return state;
  }

  async function restorePatchState(node, state) {
    if (
      node.type === "TEXT" &&
      state.fontName &&
      typeof state.fontName !== "symbol"
    )
      await figma.loadFontAsync(state.fontName);
    if (state.size && "resize" in node)
      node.resize(state.size.width, state.size.height);
    for (const [key, value] of Object.entries(state)) {
      if (key !== "size" && key !== "unrestorableMixed")
        node[key] = cloneData(value);
    }
  }

  function assertTextRange(node, start, end) {
    if (node.type !== "TEXT")
      fail("INVALID_ARGUMENT", `Node ${node.id} is not a text node.`);
    if (
      !Number.isInteger(start) ||
      !Number.isInteger(end) ||
      start < 0 ||
      end <= start ||
      end > node.characters.length ||
      end - start > maxTextRangeCharacters
    )
      fail(
        "INVALID_ARGUMENT",
        `Text range must satisfy 0 <= start < end <= ${node.characters.length} and span at most ${maxTextRangeCharacters} UTF-16 code units.`,
      );
  }

  function serializeTextSegments(node, start, end) {
    return node
      .getStyledTextSegments(
        ["fontName", "fontSize", "lineHeight", "letterSpacing", "fills"],
        start,
        end,
      )
      .map((segment) => ({
        start: segment.start,
        end: segment.end,
        characters: segment.characters,
        fontName: cloneData(segment.fontName),
        fontSize: segment.fontSize,
        lineHeight: cloneData(segment.lineHeight),
        letterSpacing: cloneData(segment.letterSpacing),
        fills: serializePaints(segment.fills),
      }));
  }

  async function textRangeCommand(input) {
    const node = await nodeById(input.nodeId);
    if (input.action === "read") {
      assertTextRange(node, input.start, input.end);
      return {
        nodeId: node.id,
        start: input.start,
        end: input.end,
        characters: node.characters.slice(input.start, input.end),
        segments: serializeTextSegments(node, input.start, input.end),
      };
    }
    const ranges = input.ranges;
    if (!Array.isArray(ranges) || ranges.length < 1 || ranges.length > 100)
      fail("INVALID_ARGUMENT", "text range update requires 1 to 100 ranges.");
    let previousEnd = -1;
    let touchedCharacters = 0;
    for (const range of ranges) {
      assertTextRange(node, range.start, range.end);
      touchedCharacters += range.end - range.start;
      if (touchedCharacters > maxTextRangeCharacters)
        fail(
          "INVALID_ARGUMENT",
          `Text range update may touch at most ${maxTextRangeCharacters} UTF-16 code units.`,
        );
      if (range.start < previousEnd)
        fail(
          "INVALID_ARGUMENT",
          "Text ranges must be sorted and non-overlapping.",
        );
      if (!range.style || Object.keys(range.style).length === 0)
        fail("INVALID_ARGUMENT", "Text range style cannot be empty.");
      previousEnd = range.end;
    }
    const snapshots = ranges.flatMap((range) =>
      serializeTextSegments(node, range.start, range.end),
    );
    const fonts = new Map();
    for (const range of ranges) {
      const values = range.style.fontName
        ? [range.style.fontName]
        : node.getRangeAllFontNames(range.start, range.end);
      for (const font of values)
        fonts.set(`${font.family}\u0000${font.style}`, font);
    }
    for (const segment of snapshots)
      fonts.set(
        `${segment.fontName.family}\u0000${segment.fontName.style}`,
        segment.fontName,
      );
    await Promise.all(
      [...fonts.values()].map((font) => figma.loadFontAsync(font)),
    );
    const apply = (start, end, style) => {
      if (style.fontName !== undefined)
        node.setRangeFontName(start, end, style.fontName);
      if (style.fontSize !== undefined)
        node.setRangeFontSize(start, end, style.fontSize);
      if (style.lineHeight !== undefined)
        node.setRangeLineHeight(start, end, style.lineHeight);
      if (style.letterSpacing !== undefined)
        node.setRangeLetterSpacing(start, end, style.letterSpacing);
      if (style.fills !== undefined)
        node.setRangeFills(start, end, style.fills);
    };
    try {
      for (const range of ranges) apply(range.start, range.end, range.style);
    } catch (error) {
      try {
        for (const segment of snapshots)
          apply(segment.start, segment.end, segment);
      } catch {
        fail(
          "UNKNOWN_OUTCOME",
          "Text range update failed and rollback was incomplete.",
        );
      }
      throw error;
    }
    recordChange("text-range-update", [node.id]);
    return {
      nodeId: node.id,
      ranges: ranges.map((range) => ({
        start: range.start,
        end: range.end,
        segments: serializeTextSegments(node, range.start, range.end),
      })),
    };
  }

  function imageMime(bytes) {
    if (
      bytes.length >= 8 &&
      [137, 80, 78, 71, 13, 10, 26, 10].every(
        (value, index) => bytes[index] === value,
      )
    )
      return "image/png";
    if (
      bytes.length >= 3 &&
      bytes[0] === 255 &&
      bytes[1] === 216 &&
      bytes[2] === 255
    )
      return "image/jpeg";
    const header = String.fromCharCode(...bytes.slice(0, 6));
    if (header === "GIF87a" || header === "GIF89a") return "image/gif";
    fail(
      "INVALID_ARGUMENT",
      "Image bytes are not a supported PNG, JPEG, or GIF.",
    );
  }

  async function imageMetadata(image, expectedMime) {
    const bytes = await image.getBytesAsync();
    const mimeType = imageMime(bytes);
    if (expectedMime && mimeType !== expectedMime)
      fail(
        "INVALID_ARGUMENT",
        `Image MIME ${expectedMime} does not match its signature ${mimeType}.`,
      );
    const size = await image.getSizeAsync();
    return {
      hash: image.hash,
      mimeType,
      byteLength: bytes.byteLength,
      width: size.width,
      height: size.height,
    };
  }

  async function imageCommand(input) {
    if (input.action === "import") {
      let bytes;
      try {
        bytes = figma.base64Decode(input.dataBase64);
      } catch {
        fail("INVALID_ARGUMENT", "Image payload is not valid base64.");
      }
      if (bytes.byteLength < 6 || bytes.byteLength > 650_000)
        fail(
          "INVALID_ARGUMENT",
          "Image payload must be from 6 through 650000 bytes.",
        );
      const detected = imageMime(bytes);
      if (detected !== input.mimeType)
        fail(
          "INVALID_ARGUMENT",
          `Image MIME ${input.mimeType} does not match its signature ${detected}.`,
        );
      let image;
      try {
        image = figma.createImage(bytes);
      } catch (error) {
        fail("INVALID_ARGUMENT", `Figma rejected the image: ${String(error)}`);
      }
      return imageMetadata(image, detected);
    }
    const image = figma.getImageByHash(input.hash);
    if (!image)
      fail("INVALID_ARGUMENT", `Image hash ${input.hash} was not found.`);
    if (input.action === "inspect") return imageMetadata(image);
    assertNodeIds(input.nodeIds);
    const nodes = await Promise.all(input.nodeIds.map(nodeById));
    for (const node of nodes) {
      if (!("fills" in node))
        fail("INVALID_ARGUMENT", `Node ${node.id} does not support fills.`);
      if (node.fills === figma.mixed)
        fail("INVALID_ARGUMENT", `Node ${node.id} has mixed fills.`);
      if (
        input.operation === "replace" &&
        (!Number.isInteger(input.index) ||
          input.index < 0 ||
          input.index >= node.fills.length)
      )
        fail(
          "INVALID_ARGUMENT",
          `Node ${node.id} has no fill at index ${input.index}.`,
        );
    }
    const snapshots = nodes.map((node) => cloneData(node.fills));
    try {
      nodes.forEach((node) => {
        const fills = [...node.fills];
        const paint = {
          type: "IMAGE",
          imageHash: image.hash,
          scaleMode: input.scaleMode,
        };
        if (input.operation === "append") fills.push(paint);
        else fills[input.index] = paint;
        node.fills = fills;
      });
    } catch (error) {
      try {
        nodes.forEach((node, index) => {
          node.fills = cloneData(snapshots[index]);
        });
      } catch {
        fail(
          "UNKNOWN_OUTCOME",
          "Image fill update failed and rollback was incomplete.",
        );
      }
      throw error;
    }
    recordChange("image-fill", input.nodeIds);
    return {
      image: await imageMetadata(image),
      nodes: await Promise.all(nodes.map((node) => serializeNode(node))),
    };
  }

  async function coreCommand(method, input) {
    if (method === "document.summary") {
      return revisionCached("document.summary", async () => {
        await figma.loadAllPagesAsync();
        const byType = {};
        let nodeCount = 0;
        const visit = (node) => {
          nodeCount += 1;
          countSceneTraversal();
          byType[node.type] = (byType[node.type] || 0) + 1;
          if (hasChildren(node)) node.children.forEach(visit);
        };
        visit(figma.root);
        return {
          document: {
            id: figma.root.id,
            name: figma.root.name,
            type: figma.root.type,
          },
          nodeCount,
          byType,
        };
      });
    }
    if (method === "document.get") {
      await figma.loadAllPagesAsync();
      return serializeNode(figma.root, true);
    }
    if (method === "selection.get")
      return figma.currentPage.selection.map((node) => node.id);
    if (method === "changes.get") return getChanges();
    if (method === "node.text_range") return textRangeCommand(input);
    if (method === "node.image") return imageCommand(input);
    if (method === "node.query") return queryNodes(input);
    if (method === "node.get") {
      assertNodeIds(input.nodeIds);
      return Promise.all(
        input.nodeIds.map(async (id) => serializeNode(await nodeById(id))),
      );
    }
    if (method === "node.export") {
      assertNodeIds(input.nodeIds);
      const format = input.format;
      if (!exportFormats.includes(format))
        fail("INVALID_ARGUMENT", `Unsupported export format ${format}.`);
      const raster = format === "PNG" || format === "JPG";
      if (
        raster &&
        (typeof input.scale !== "number" ||
          !Number.isFinite(input.scale) ||
          input.scale <= 0 ||
          input.scale > 4)
      )
        fail(
          "INVALID_ARGUMENT",
          "Raster export scale must be greater than 0 and at most 4.",
        );
      if (!raster && input.scale !== undefined)
        fail("INVALID_ARGUMENT", `${format} export does not accept scale.`);

      const nodes = await Promise.all(input.nodeIds.map(nodeById));
      const settings = raster
        ? {
            format,
            constraint: { type: "SCALE", value: input.scale },
          }
        : { format };
      const results = [];
      for (const node of nodes) {
        if (typeof node.exportAsync !== "function")
          fail("UNSUPPORTED_BY_BRIDGE", `Node ${node.id} cannot be exported.`);
        const bytes = await node.exportAsync(settings);
        if (bytes.byteLength > maxExportBytes) {
          const recovery = raster
            ? "lower the scale"
            : `reduce the source complexity or export ${format} content as PNG/JPG`;
          fail(
            "INVALID_ARGUMENT",
            `Export for node ${node.id} is ${bytes.byteLength} bytes; ${recovery} to stay at or below ${maxExportBytes} bytes.`,
          );
        }
        results.push({
          nodeId: node.id,
          nodeName: node.name,
          format,
          mimeType: exportMimeTypes[format],
          byteLength: bytes.byteLength,
          dataBase64: figma.base64Encode(bytes),
        });
      }
      return results;
    }
    if (method === "node.create") {
      const parent = await nodeById(input.parentId);
      if (!hasChildren(parent) || typeof parent.appendChild !== "function") {
        fail(
          "INVALID_ARGUMENT",
          `Parent ${input.parentId} cannot contain children.`,
        );
      }
      if (input.dryRun) {
        return [
          {
            id: "preview:new",
            type: input.nodeType,
            name: input.name || input.nodeType,
            parentId: parent.id,
            ...input.props,
          },
        ];
      }
      const node = createByType(input.nodeType);
      try {
        await validateProps(node, input.props);
        parent.appendChild(node);
        if (input.name) node.name = input.name;
        await applyProps(node, input.props);
      } catch (error) {
        node.remove();
        throw error;
      }
      recordChange("create", [node.id]);
      return [await serializeNode(node)];
    }
    assertNodeIds(input.nodeIds);
    const nodes = await Promise.all(input.nodeIds.map(nodeById));
    if (input.dryRun) {
      if (method === "node.update") {
        await Promise.all(
          nodes.map((node) => validateProps(node, input.patch)),
        );
        return Promise.all(
          nodes.map(async (node) => ({
            ...(await serializeNode(node)),
            ...cloneData(input.patch),
          })),
        );
      }
      if (method === "node.move") {
        let parent;
        if (input.parentId) {
          parent = await nodeById(input.parentId);
          if (!hasChildren(parent) || typeof parent.insertChild !== "function")
            fail("INVALID_ARGUMENT", "Target parent cannot contain children.");
        }
        return Promise.all(
          nodes.map(async (node) => ({
            ...(await serializeNode(node)),
            ...(parent ? { parentId: parent.id } : {}),
            ...(input.x !== undefined ? { x: input.x } : {}),
            ...(input.y !== undefined ? { y: input.y } : {}),
          })),
        );
      }
      if (method === "node.resize") {
        for (const node of nodes)
          if (!("resize" in node))
            fail("INVALID_ARGUMENT", `Node ${node.id} cannot be resized.`);
        return Promise.all(
          nodes.map(async (node) => ({
            ...(await serializeNode(node)),
            width: input.size.width,
            height: input.size.height,
          })),
        );
      }
      if (method === "node.clone") {
        let parent;
        if (input.parentId) {
          parent = await nodeById(input.parentId);
          if (!hasChildren(parent) || typeof parent.appendChild !== "function")
            fail("INVALID_ARGUMENT", "Clone parent cannot contain children.");
        }
        return Promise.all(
          nodes.map(async (node) => {
            const snapshot = await serializeNode(node);
            return {
              ...snapshot,
              id: `preview:${node.id}`,
              ...(parent ? { parentId: parent.id } : {}),
              ...(input.offset && "x" in node
                ? { x: node.x + input.offset.x }
                : {}),
              ...(input.offset && "y" in node
                ? { y: node.y + input.offset.y }
                : {}),
            };
          }),
        );
      }
      if (method === "node.delete") return [...input.nodeIds];
    }
    if (method === "node.update") {
      await Promise.all(nodes.map((node) => validateProps(node, input.patch)));
      const snapshots = new Map(
        nodes.map((node) => [node.id, capturePatchState(node, input.patch)]),
      );
      try {
        for (const node of nodes) await applyProps(node, input.patch);
      } catch (error) {
        const rollback = await Promise.allSettled(
          nodes.map((node) => restorePatchState(node, snapshots.get(node.id))),
        );
        const hasUnrestorableMixed = [...snapshots.values()].some(
          (state) => state.unrestorableMixed.length > 0,
        );
        if (
          hasUnrestorableMixed ||
          rollback.some((result) => result.status === "rejected")
        )
          fail(
            "UNKNOWN_OUTCOME",
            "Node update failed and rollback could not restore every node.",
          );
        throw error;
      }
      recordChange("update", input.nodeIds);
      return Promise.all(nodes.map((node) => serializeNode(node)));
    }
    if (method === "node.move") {
      let parent;
      if (input.parentId) {
        parent = await nodeById(input.parentId);
        if (!hasChildren(parent) || typeof parent.insertChild !== "function")
          fail("INVALID_ARGUMENT", "Target parent cannot contain children.");
      }
      for (const node of nodes) {
        if (input.x !== undefined && !("x" in node))
          fail("INVALID_ARGUMENT", `Node ${node.id} cannot be positioned.`);
        if (input.y !== undefined && !("y" in node))
          fail("INVALID_ARGUMENT", `Node ${node.id} cannot be positioned.`);
      }
      nodes.forEach((node, offset) => {
        if (parent)
          parent.insertChild(
            (input.index ?? parent.children.length) + offset,
            node,
          );
        if (input.x !== undefined && "x" in node) node.x = input.x;
        if (input.y !== undefined && "y" in node) node.y = input.y;
      });
      recordChange("move", input.nodeIds);
      return Promise.all(nodes.map((node) => serializeNode(node)));
    }
    if (method === "node.resize") {
      for (const node of nodes)
        if (!("resize" in node))
          fail("INVALID_ARGUMENT", `Node ${node.id} cannot be resized.`);
      for (const node of nodes) {
        node.resize(input.size.width, input.size.height);
      }
      recordChange("resize", input.nodeIds);
      return Promise.all(nodes.map((node) => serializeNode(node)));
    }
    if (method === "node.clone") {
      for (const node of nodes)
        if (!("clone" in node))
          fail("UNSUPPORTED_BY_BRIDGE", `Node ${node.id} cannot be cloned.`);
      let cloneParent;
      if (input.parentId) {
        cloneParent = await nodeById(input.parentId);
        if (
          !hasChildren(cloneParent) ||
          typeof cloneParent.appendChild !== "function"
        )
          fail("INVALID_ARGUMENT", "Clone parent cannot contain children.");
      }
      const clones = nodes.map((node) => ({ clone: node.clone() }));
      for (const entry of clones) {
        if (cloneParent) cloneParent.appendChild(entry.clone);
        if (input.offset && "x" in entry.clone) entry.clone.x += input.offset.x;
        if (input.offset && "y" in entry.clone) entry.clone.y += input.offset.y;
      }
      recordChange(
        "clone",
        clones.map((entry) => entry.clone.id),
      );
      return Promise.all(clones.map((entry) => serializeNode(entry.clone)));
    }
    if (method === "node.delete") {
      for (const node of nodes) node.remove();
      recordChange("delete", input.nodeIds);
      return input.nodeIds;
    }
    fail("UNSUPPORTED_BY_BRIDGE", `Unknown core method ${method}.`);
  }
  return { command: coreCommand };
}

// Source: plugin/domains/layout.js
function createLayoutDomain({
  fail,
  assertNodeIds,
  cloneData,
  countSceneTraversal,
  recordChange,
  nodeById,
  hasChildren,
  parentId,
  toPluginConstraints,
  fromPluginConstraints,
}) {
  function padding(layout) {
    if (typeof layout.padding === "number") {
      return {
        top: layout.padding,
        right: layout.padding,
        bottom: layout.padding,
        left: layout.padding,
      };
    }
    return layout.padding;
  }

  function applyLayout(node, layout) {
    if (!("layoutMode" in node))
      fail("INVALID_ARGUMENT", `Node ${node.id} does not support Auto Layout.`);
    node.layoutMode = layout.layoutMode;
    if (layout.gap !== undefined || layout.itemSpacing !== undefined)
      node.itemSpacing = layout.gap ?? layout.itemSpacing;
    const pad = padding(layout);
    if (pad) {
      node.paddingTop = pad.top;
      node.paddingRight = pad.right;
      node.paddingBottom = pad.bottom;
      node.paddingLeft = pad.left;
    }
    for (const key of [
      "primaryAxisAlignItems",
      "counterAxisAlignItems",
      "layoutWrap",
      "primaryAxisSizingMode",
      "counterAxisSizingMode",
    ])
      if (layout[key] !== undefined) node[key] = layout[key];
  }

  function applySizing(node, sizing) {
    if (!("layoutSizingHorizontal" in node))
      fail(
        "INVALID_ARGUMENT",
        `Node ${node.id} does not support layout sizing.`,
      );
    node.layoutSizingHorizontal = sizing.horizontal;
    node.layoutSizingVertical = sizing.vertical;
    for (const key of [
      "minWidth",
      "maxWidth",
      "minHeight",
      "maxHeight",
      "layoutAlign",
    ]) {
      if (sizing[key] !== undefined) node[key] = sizing[key];
    }
  }

  function layoutSnapshot(node) {
    const parent = parentId(node);
    return {
      nodeId: node.id,
      name: node.name,
      ...(parent ? { parentId: parent } : {}),
      childIds: hasChildren(node) ? node.children.map((child) => child.id) : [],
      layout: {
        layoutMode: "layoutMode" in node ? node.layoutMode : "NONE",
        gap: "itemSpacing" in node ? (node.itemSpacing ?? 0) : 0,
        itemSpacing: "itemSpacing" in node ? (node.itemSpacing ?? 0) : 0,
        padding: {
          top: "paddingTop" in node ? (node.paddingTop ?? 0) : 0,
          right: "paddingRight" in node ? (node.paddingRight ?? 0) : 0,
          bottom: "paddingBottom" in node ? (node.paddingBottom ?? 0) : 0,
          left: "paddingLeft" in node ? (node.paddingLeft ?? 0) : 0,
        },
        primaryAxisAlignItems:
          "primaryAxisAlignItems" in node
            ? (node.primaryAxisAlignItems ?? "MIN")
            : "MIN",
        counterAxisAlignItems:
          "counterAxisAlignItems" in node
            ? (node.counterAxisAlignItems ?? "MIN")
            : "MIN",
        layoutWrap:
          "layoutWrap" in node ? (node.layoutWrap ?? "NO_WRAP") : "NO_WRAP",
        primaryAxisSizingMode:
          "primaryAxisSizingMode" in node
            ? (node.primaryAxisSizingMode ?? "FIXED")
            : "FIXED",
        counterAxisSizingMode:
          "counterAxisSizingMode" in node
            ? (node.counterAxisSizingMode ?? "FIXED")
            : "FIXED",
      },
      sizing: {
        horizontal:
          "layoutSizingHorizontal" in node
            ? (node.layoutSizingHorizontal ?? "FIXED")
            : "FIXED",
        vertical:
          "layoutSizingVertical" in node
            ? (node.layoutSizingVertical ?? "FIXED")
            : "FIXED",
        ...(node.minWidth !== undefined ? { minWidth: node.minWidth } : {}),
        ...(node.maxWidth !== undefined ? { maxWidth: node.maxWidth } : {}),
        ...(node.minHeight !== undefined ? { minHeight: node.minHeight } : {}),
        ...(node.maxHeight !== undefined ? { maxHeight: node.maxHeight } : {}),
        ...(node.layoutAlign !== undefined
          ? { layoutAlign: node.layoutAlign }
          : {}),
        ...(node.layoutPositioning !== undefined
          ? { layoutPositioning: node.layoutPositioning }
          : {}),
      },
      constraints:
        "constraints" in node
          ? fromPluginConstraints(node.constraints)
          : { horizontal: "LEFT", vertical: "TOP" },
    };
  }

  /**
   * @param {BaseNode} node
   * @returns {node is FrameNode | ComponentNode | ComponentSetNode | InstanceNode}
   */
  function isAutoLayoutContainer(node) {
    return ["FRAME", "COMPONENT", "COMPONENT_SET", "INSTANCE"].includes(
      node.type,
    );
  }

  function parentAxisSizing(node, axis) {
    const primary =
      (node.layoutMode === "HORIZONTAL" && axis === "horizontal") ||
      (node.layoutMode === "VERTICAL" && axis === "vertical");
    return primary
      ? (node.primaryAxisSizingMode ?? "FIXED")
      : (node.counterAxisSizingMode ?? "FIXED");
  }

  function childExtent(node, axis) {
    const sizing =
      axis === "horizontal"
        ? node.layoutSizingHorizontal
        : node.layoutSizingVertical;
    const minimum = axis === "horizontal" ? node.minWidth : node.minHeight;
    if (sizing === "FILL") return minimum ?? 0;
    return (axis === "horizontal" ? node.width : node.height) ?? minimum ?? 0;
  }

  function validateNode(node) {
    const issues = [];
    const parent = node.parent;
    const parentAuto =
      parent && "layoutMode" in parent && parent.layoutMode !== "NONE";
    if (
      "layoutSizingHorizontal" in node &&
      node.layoutPositioning !== "ABSOLUTE"
    ) {
      for (const axis of ["horizontal", "vertical"]) {
        const property =
          axis === "horizontal"
            ? "layoutSizingHorizontal"
            : "layoutSizingVertical";
        const sizing = node[property];
        if (sizing !== "HUG" && sizing !== "FILL") continue;
        if (!parentAuto) {
          issues.push({
            code:
              sizing === "HUG"
                ? "HUG_WITHOUT_AUTO_LAYOUT_PARENT"
                : "FILL_WITHOUT_AUTO_LAYOUT_PARENT",
            nodeId: node.id,
            axis,
            repairable: true,
            message: `${sizing} requires an Auto Layout parent.`,
            details: { property, parentId: parent?.id, current: sizing },
          });
        } else if (
          sizing === "FILL" &&
          parentAxisSizing(parent, axis) === "AUTO"
        ) {
          issues.push({
            code:
              axis === "horizontal"
                ? "FILL_IN_HUG_PARENT_HORIZONTAL"
                : "FILL_IN_HUG_PARENT_VERTICAL",
            nodeId: node.id,
            axis,
            repairable: true,
            message: `FILL on ${axis} conflicts with a hugging parent.`,
            details: { property, parentId: parent.id, current: sizing },
          });
        }
      }
    }
    if (
      "minWidth" in node &&
      node.minWidth != null &&
      node.maxWidth != null &&
      node.minWidth > node.maxWidth
    ) {
      issues.push({
        code: "MIN_MAX_CONFLICT_WIDTH",
        nodeId: node.id,
        axis: "horizontal",
        repairable: false,
        message: "minWidth is greater than maxWidth.",
        details: { minimum: node.minWidth, maximum: node.maxWidth },
      });
    }
    if (
      "minHeight" in node &&
      node.minHeight != null &&
      node.maxHeight != null &&
      node.minHeight > node.maxHeight
    ) {
      issues.push({
        code: "MIN_MAX_CONFLICT_HEIGHT",
        nodeId: node.id,
        axis: "vertical",
        repairable: false,
        message: "minHeight is greater than maxHeight.",
        details: { minimum: node.minHeight, maximum: node.maxHeight },
      });
    }
    if (
      isAutoLayoutContainer(node) &&
      node.layoutMode !== "NONE" &&
      node.layoutWrap !== "WRAP" &&
      hasChildren(node)
    ) {
      const children = node.children.filter(
        (child) =>
          child.visible !== false &&
          (!("layoutPositioning" in child) ||
            child.layoutPositioning !== "ABSOLUTE"),
      );
      if (children.length > 0) {
        const gap = node.itemSpacing ?? 0;
        const horizontal = node.layoutMode === "HORIZONTAL";
        const requiredHorizontal =
          node.paddingLeft +
          node.paddingRight +
          (horizontal
            ? children.reduce(
                (sum, child) => sum + childExtent(child, "horizontal"),
                0,
              ) +
              gap * Math.max(0, children.length - 1)
            : Math.max(
                ...children.map((child) => childExtent(child, "horizontal")),
              ));
        const requiredVertical =
          node.paddingTop +
          node.paddingBottom +
          (horizontal
            ? Math.max(
                ...children.map((child) => childExtent(child, "vertical")),
              )
            : children.reduce(
                (sum, child) => sum + childExtent(child, "vertical"),
                0,
              ) +
              gap * Math.max(0, children.length - 1));
        for (const [axis, required, available] of [
          ["horizontal", requiredHorizontal, node.width],
          ["vertical", requiredVertical, node.height],
        ]) {
          if (
            parentAxisSizing(node, axis) === "FIXED" &&
            required > available
          ) {
            issues.push({
              code:
                axis === "horizontal"
                  ? "AUTO_LAYOUT_OVERFLOW_HORIZONTAL"
                  : "AUTO_LAYOUT_OVERFLOW_VERTICAL",
              nodeId: node.id,
              axis,
              repairable: false,
              message: `Auto Layout node overflows its ${axis} bounds.`,
              details: {
                required,
                available,
                overflowBy: required - available,
              },
            });
          }
        }
      }
    }
    return issues;
  }

  function collectLayoutScope(nodes) {
    const result = [];
    const visited = new Set();
    const visit = (node) => {
      if (visited.has(node.id)) return;
      visited.add(node.id);
      countSceneTraversal();
      result.push(node);
      if (hasChildren(node)) node.children.forEach(visit);
    };
    nodes.forEach(visit);
    return result;
  }

  function validateLayoutScope(nodes) {
    const issues = collectLayoutScope(nodes).flatMap(validateNode);
    return { valid: issues.length === 0, issues };
  }

  function assertLayoutOperation(node, operation, plannedAutoLayoutParents) {
    if (operation.op === "apply" && !("layoutMode" in node))
      fail("INVALID_ARGUMENT", `Node ${node.id} does not support Auto Layout.`);
    if (operation.op === "sizing") {
      if (!("layoutSizingHorizontal" in node))
        fail(
          "INVALID_ARGUMENT",
          `Node ${node.id} does not support layout sizing.`,
        );
      const automatic =
        operation.sizing.horizontal !== "FIXED" ||
        operation.sizing.vertical !== "FIXED";
      const parent = node.parent;
      if (
        automatic &&
        (!parent ||
          ((!("layoutMode" in parent) || parent.layoutMode === "NONE") &&
            !plannedAutoLayoutParents.has(parent.id)))
      )
        fail(
          "INVALID_ARGUMENT",
          `Node ${node.id} requires an Auto Layout parent for HUG or FILL sizing.`,
        );
      const minWidth = operation.sizing.minWidth ?? node.minWidth;
      const maxWidth = operation.sizing.maxWidth ?? node.maxWidth;
      const minHeight = operation.sizing.minHeight ?? node.minHeight;
      const maxHeight = operation.sizing.maxHeight ?? node.maxHeight;
      if (minWidth != null && maxWidth != null && minWidth > maxWidth)
        fail("INVALID_ARGUMENT", "minWidth must not exceed maxWidth.");
      if (minHeight != null && maxHeight != null && minHeight > maxHeight)
        fail("INVALID_ARGUMENT", "minHeight must not exceed maxHeight.");
    }
    if (operation.op === "constraints" && !("constraints" in node))
      fail("INVALID_ARGUMENT", `Node ${node.id} does not support constraints.`);
  }

  function nodeDepth(node) {
    let depth = 0;
    let current = node.parent;
    while (current) {
      depth += 1;
      current = current.parent;
    }
    return depth;
  }

  function applyLayoutPreview(snapshot, layout) {
    snapshot.layout.layoutMode = layout.layoutMode;
    const gap = layout.gap ?? layout.itemSpacing;
    if (gap !== undefined) {
      snapshot.layout.gap = gap;
      snapshot.layout.itemSpacing = gap;
    }
    const pad = padding(layout);
    if (pad) snapshot.layout.padding = { ...pad };
    for (const key of [
      "primaryAxisAlignItems",
      "counterAxisAlignItems",
      "layoutWrap",
      "primaryAxisSizingMode",
      "counterAxisSizingMode",
    ])
      if (layout[key] !== undefined) snapshot.layout[key] = layout[key];
  }

  function applySizingPreview(snapshot, sizing) {
    snapshot.sizing.horizontal = sizing.horizontal;
    snapshot.sizing.vertical = sizing.vertical;
    for (const key of [
      "minWidth",
      "maxWidth",
      "minHeight",
      "maxHeight",
      "layoutAlign",
    ])
      if (sizing[key] !== undefined) snapshot.sizing[key] = sizing[key];
  }

  function captureLayoutState(node) {
    const state = {};
    for (const key of [
      "layoutMode",
      "itemSpacing",
      "paddingTop",
      "paddingRight",
      "paddingBottom",
      "paddingLeft",
      "primaryAxisAlignItems",
      "counterAxisAlignItems",
      "layoutWrap",
      "primaryAxisSizingMode",
      "counterAxisSizingMode",
      "layoutSizingHorizontal",
      "layoutSizingVertical",
      "minWidth",
      "maxWidth",
      "minHeight",
      "maxHeight",
      "layoutAlign",
      "constraints",
    ])
      if (key in node) state[key] = cloneData(node[key]);
    return state;
  }

  function restoreLayoutState(node, state) {
    for (const [key, value] of Object.entries(state)) node[key] = value;
  }

  async function layoutCommand(input) {
    if (input.action !== "batch") assertNodeIds(input.nodeIds);
    const directNodes =
      input.action === "batch"
        ? []
        : await Promise.all(input.nodeIds.map(nodeById));
    if (input.action === "inspect")
      return { layouts: await Promise.all(directNodes.map(layoutSnapshot)) };
    if (input.action === "validate") return validateLayoutScope(directNodes);
    if (input.action === "repair") {
      const repairableCodes = new Set([
        "FILL_IN_HUG_PARENT_HORIZONTAL",
        "FILL_IN_HUG_PARENT_VERTICAL",
        "HUG_WITHOUT_AUTO_LAYOUT_PARENT",
        "FILL_WITHOUT_AUTO_LAYOUT_PARENT",
      ]);
      const unsafeCodes = [...new Set(input.issueCodes)].filter(
        (code) => !repairableCodes.has(code),
      );
      if (unsafeCodes.length)
        fail(
          "INVALID_ARGUMENT",
          "Requested layout repair includes unsafe issue codes.",
          false,
          { issueCodes: unsafeCodes },
        );
      const beforeValidation = validateLayoutScope(directNodes);
      const selected = beforeValidation.issues.filter((issue) =>
        input.issueCodes.includes(issue.code),
      );
      const repairs = selected.map((issue) => ({
        issueCode: issue.code,
        nodeId: issue.nodeId,
        reason: issue.message,
        changes: [
          {
            property: issue.details.property,
            from: issue.details.current,
            to: "FIXED",
          },
        ],
      }));
      if (input.dryRun) {
        const selectedKeys = new Set(
          selected.map(
            (issue) => `${issue.code}:${issue.nodeId}:${issue.axis}`,
          ),
        );
        const issues = beforeValidation.issues.filter(
          (issue) =>
            !selectedKeys.has(`${issue.code}:${issue.nodeId}:${issue.axis}`),
        );
        return {
          beforeValidation,
          repairs,
          afterValidation: { valid: issues.length === 0, issues },
          dryRun: true,
        };
      }

      const repairedNodeMap = new Map();
      for (const issue of selected) {
        const node = await nodeById(issue.nodeId);
        repairedNodeMap.set(node.id, node);
      }
      const repairedNodes = [...repairedNodeMap.values()];
      const originals = new Map(
        repairedNodes.map((node) => [node.id, captureLayoutState(node)]),
      );
      try {
        for (const issue of selected) {
          const node = await nodeById(issue.nodeId);
          node[issue.details.property] = "FIXED";
        }
        const afterValidation = validateLayoutScope(directNodes);
        const unresolved = afterValidation.issues.filter((issue) =>
          input.issueCodes.includes(issue.code),
        );
        if (repairs.length > 0 && unresolved.length > 0)
          fail(
            "INTERNAL_ERROR",
            "Auto Layout repair did not clear every selected issue.",
            false,
            { unresolvedIssues: unresolved },
          );
        if (repairs.length) recordChange("layout.repair", input.nodeIds);
        return {
          beforeValidation,
          repairs,
          afterValidation,
          dryRun: false,
        };
      } catch (error) {
        for (const node of repairedNodes) {
          const original = originals.get(node.id);
          if (original) restoreLayoutState(node, original);
        }
        throw error;
      }
    }

    const operations =
      input.action === "batch"
        ? input.operations
        : input.action === "apply"
          ? [{ op: "apply", nodeIds: input.nodeIds, layout: input.layout }]
          : [{ op: "sizing", nodeIds: input.nodeIds, sizing: input.sizing }];
    for (const operation of operations) assertNodeIds(operation.nodeIds);
    const units = [];
    const plannedAutoLayoutParents = new Set(
      operations
        .filter(
          (operation) =>
            operation.op === "apply" && operation.layout.layoutMode !== "NONE",
        )
        .flatMap((operation) => operation.nodeIds),
    );
    for (const [operationIndex, operation] of operations.entries()) {
      for (const [nodeIndex, nodeId] of operation.nodeIds.entries()) {
        const node = await nodeById(nodeId);
        assertLayoutOperation(node, operation, plannedAutoLayoutParents);
        units.push({ operation, operationIndex, nodeIndex, node });
      }
    }
    const phase = { apply: 0, sizing: 1, constraints: 2 };
    units.sort((left, right) => {
      const phaseDifference =
        phase[left.operation.op] - phase[right.operation.op];
      if (phaseDifference !== 0) return phaseDifference;
      const depthDifference = nodeDepth(left.node) - nodeDepth(right.node);
      if (depthDifference !== 0) return depthDifference;
      return (
        left.operationIndex - right.operationIndex ||
        left.nodeIndex - right.nodeIndex
      );
    });
    const targetNodes = [
      ...new Map(units.map((unit) => [unit.node.id, unit.node])).values(),
    ].sort(
      (left, right) =>
        nodeDepth(left) - nodeDepth(right) || left.id.localeCompare(right.id),
    );
    const targetIds = targetNodes.map((node) => node.id);
    const before = targetNodes.map(layoutSnapshot);
    const appliedOrder = units.map(
      (unit) => `${unit.operation.op}:${unit.node.id}`,
    );

    if (input.dryRun) {
      const previews = new Map(
        before.map((snapshot) => [snapshot.nodeId, cloneData(snapshot)]),
      );
      for (const { operation, node } of units) {
        const snapshot = previews.get(node.id);
        if (operation.op === "apply")
          applyLayoutPreview(snapshot, operation.layout);
        else if (operation.op === "sizing")
          applySizingPreview(snapshot, operation.sizing);
        else snapshot.constraints = { ...operation.constraints };
      }
      return {
        before,
        after: targetIds.map((nodeId) => previews.get(nodeId)),
        appliedOrder,
        dryRun: true,
      };
    }

    const originals = new Map(
      targetNodes.map((node) => [node.id, captureLayoutState(node)]),
    );
    try {
      for (const { operation, node } of units) {
        if (operation.op === "apply") applyLayout(node, operation.layout);
        else if (operation.op === "sizing") applySizing(node, operation.sizing);
        else if ("constraints" in node)
          node.constraints = toPluginConstraints(operation.constraints);
      }
      const after = targetNodes.map(layoutSnapshot);
      recordChange(`layout.${input.action}`, targetIds);
      return { before, after, appliedOrder, dryRun: false };
    } catch (error) {
      for (const node of targetNodes) {
        const original = originals.get(node.id);
        if (original) restoreLayoutState(node, original);
      }
      throw error;
    }
  }
  return { command: layoutCommand };
}

// Source: plugin/domains/component.js
function createComponentDomain({
  figma,
  fail,
  revisionCached,
  countSceneTraversal,
  recordChange,
  nodeById,
  hasChildren,
  serializeNode,
}) {
  function definitionsFor(node) {
    try {
      return node.componentPropertyDefinitions || {};
    } catch {
      if (node.type === "COMPONENT" && node.parent?.type === "COMPONENT_SET")
        return node.parent.componentPropertyDefinitions || {};
      return {};
    }
  }

  function componentProperties(definitions) {
    return Object.fromEntries(
      Object.entries(definitions || {}).map(([name, definition]) => [
        name,
        {
          type: definition.type,
          defaultValue: definition.defaultValue,
          ...(definition.variantOptions
            ? { options: [...definition.variantOptions] }
            : definition.preferredValues
              ? {
                  options: definition.preferredValues.map((value) => value.key),
                }
              : {}),
          ...(definition.description !== undefined
            ? { description: definition.description }
            : {}),
          ...(definition.slotSettings
            ? { slotSettings: { ...definition.slotSettings } }
            : {}),
        },
      ]),
    );
  }

  async function importPublishedComponent(componentKey, kind) {
    let timeout;
    try {
      return await Promise.race([
        kind === "COMPONENT"
          ? figma.importComponentByKeyAsync(componentKey)
          : figma.importComponentSetByKeyAsync(componentKey),
        new Promise((_, reject) => {
          timeout = setTimeout(
            () => reject(new Error("Figma library import timed out.")),
            4000,
          );
        }),
      ]);
    } catch (error) {
      const timedOut = error?.message === "Figma library import timed out.";
      fail(
        timedOut ? "UNKNOWN_OUTCOME" : "LIBRARY_IMPORT_FAILED",
        timedOut
          ? "Figma library import timed out, but the uncancellable import may still complete."
          : "Figma could not import the published component key.",
        false,
        {
          reason: timedOut ? "TIMEOUT_PENDING" : "PLAN_ACCESS_OR_KEY",
          kind,
          componentKey,
        },
      );
    } finally {
      if (timeout !== undefined) clearTimeout(timeout);
    }
  }

  async function localComponents() {
    await figma.loadAllPagesAsync();
    return figma.root.findAllWithCriteria({
      types: ["COMPONENT", "COMPONENT_SET"],
    });
  }

  /** @param {ComponentNode | ComponentSetNode} node */
  function componentRecord(node) {
    return {
      source: node.remote ? "library" : "local",
      kind: node.type,
      name: node.name,
      nodeId: node.id,
      key: node.key,
      description: node.description,
      properties: componentProperties(definitionsFor(node)),
    };
  }

  async function componentCommand(input) {
    if (input.action === "search") {
      const query = (input.query || "").toLowerCase();
      const inventory = await revisionCached(
        "component.inventory",
        async () => {
          const components = await localComponents();
          countSceneTraversal(components.length);
          return components.map(componentRecord);
        },
      );
      return {
        components: inventory.filter((component) =>
          component.name.toLowerCase().includes(query),
        ),
      };
    }
    if (input.action === "inspect") {
      let node;
      if (input.componentId) node = await nodeById(input.componentId);
      else {
        const components = await localComponents();
        countSceneTraversal(components.length);
        node = components.find((item) => item.key === input.componentKey);
      }
      if (node?.type !== "COMPONENT" && node?.type !== "COMPONENT_SET")
        fail("NODE_NOT_FOUND", "Component or component set was not found.");
      return {
        component: componentRecord(node),
        node: await serializeNode(node, true),
      };
    }
    if (
      input.action === "library_search" ||
      input.action === "library_inspect"
    ) {
      fail(
        "LIBRARY_SEARCH_UNAVAILABLE",
        "Figma Plugin API cannot enumerate component libraries. Use a published key with library_import.",
        false,
        { reason: "NO_COMPONENT_LIBRARY_INVENTORY_API" },
      );
    }
    if (input.action === "library_import") {
      if (input.dryRun)
        return {
          dryRun: true,
          action: input.action,
          componentKey: input.componentKey,
          kind: input.kind,
        };
      const imported = await importPublishedComponent(
        input.componentKey,
        input.kind,
      );
      recordChange("component.library_import", [imported.id]);
      return {
        imported: componentRecord(imported),
        node: await serializeNode(imported, true),
      };
    }
    if (input.dryRun) return { dryRun: true, action: input.action };
    if (input.action === "create_set") {
      const parent = await nodeById(input.parentId);
      if (!hasChildren(parent))
        fail(
          "INVALID_ARGUMENT",
          "Component set parent cannot contain children.",
        );
      const entries = Object.entries(input.axes);
      if (
        entries.length < 1 ||
        entries.length > 8 ||
        entries.some(
          ([axis, values]) =>
            !axis.trim() ||
            !Array.isArray(values) ||
            values.length < 1 ||
            values.length > 20 ||
            new Set(values).size !== values.length,
        )
      )
        fail(
          "INVALID_ARGUMENT",
          "Component set requires 1 to 8 axes with 1 to 20 unique values each.",
        );
      const combinations = entries.reduce(
        (sets, [axis, values]) =>
          sets.flatMap((combination) =>
            values.map((value) => ({ ...combination, [axis]: value })),
          ),
        [{}],
      );
      if (combinations.length > 100)
        fail(
          "INVALID_ARGUMENT",
          "A component set may contain at most 100 variants.",
        );
      const variants = [];
      let set;
      try {
        for (const combination of combinations) {
          const component = figma.createComponent();
          variants.push(component);
          component.name = Object.entries(combination)
            .map(([key, value]) => `${key}=${value}`)
            .join(", ");
          parent.appendChild(component);
        }
        set = figma.combineAsVariants(variants, parent);
        set.name = input.name;
        recordChange("component.create_set", [set.id]);
        return { componentSet: await serializeNode(set, true) };
      } catch (error) {
        if (set?.parent) set.remove();
        else {
          for (const variant of variants) {
            if (variant.parent && variant.type === "COMPONENT")
              variant.remove();
          }
        }
        throw error;
      }
    }
    if (input.action === "arrange_set") {
      const set = await nodeById(input.componentSetId);
      if (set.type !== "COMPONENT_SET")
        fail("INVALID_ARGUMENT", "Target is not a component set.");
      const columns =
        input.columns || Math.ceil(Math.sqrt(set.children.length));
      const gap = input.gap ?? 24;
      set.children.forEach((child, index) => {
        child.x = (index % columns) * (child.width + gap);
        child.y = Math.floor(index / columns) * (child.height + gap);
      });
      recordChange("component.arrange_set", [set.id]);
      return { componentSet: await serializeNode(set, true) };
    }
    const component = await nodeById(input.componentId);
    if (component.type !== "COMPONENT" && component.type !== "COMPONENT_SET")
      fail("INVALID_ARGUMENT", "Target is not a component or component set.");
    if (input.action === "set_description")
      component.description = input.description;
    if (input.action === "property_add") {
      if (definitionsFor(component)[input.propertyName])
        fail("INVALID_ARGUMENT", "Component property already exists.");
      if (input.property.type === "VARIANT" || input.property.type === "SLOT")
        fail(
          "UNSUPPORTED_BY_BRIDGE",
          input.property.type === "VARIANT"
            ? "Figma derives VARIANT properties from component-set child names."
            : "Use slot_create so Figma creates a physical SlotNode with its property definition.",
        );
      if (
        input.property.options &&
        input.property.type !== "INSTANCE_SWAP" &&
        input.property.type !== "SLOT"
      )
        fail(
          "INVALID_ARGUMENT",
          "Preferred component keys are only valid for INSTANCE_SWAP and SLOT properties.",
        );
      component.addComponentProperty(
        input.propertyName,
        input.property.type,
        input.property.defaultValue,
        {
          ...(input.property.options
            ? {
                preferredValues: input.property.options.map((key) => ({
                  type: "COMPONENT",
                  key,
                })),
              }
            : {}),
          ...(input.property.description !== undefined
            ? { description: input.property.description }
            : {}),
          ...(input.property.slotSettings
            ? { slotSettings: input.property.slotSettings }
            : {}),
        },
      );
    }
    if (input.action === "property_update") {
      if (!definitionsFor(component)[input.propertyName])
        fail("INVALID_ARGUMENT", "Component property was not found.");
      if (input.patch.type !== undefined)
        fail(
          "INVALID_ARGUMENT",
          "Figma cannot change a component property type.",
        );
      component.editComponentProperty(input.propertyName, {
        ...(input.patch.defaultValue !== undefined
          ? { defaultValue: input.patch.defaultValue }
          : {}),
        ...(input.patch.options
          ? {
              preferredValues: input.patch.options.map((key) => ({
                type: "COMPONENT",
                key,
              })),
            }
          : {}),
        ...(input.patch.description !== undefined
          ? { description: input.patch.description }
          : {}),
        ...(input.patch.slotSettings
          ? { slotSettings: input.patch.slotSettings }
          : {}),
      });
    }
    if (input.action === "property_delete") {
      if (!definitionsFor(component)[input.propertyName])
        fail("INVALID_ARGUMENT", "Component property was not found.");
      component.deleteComponentProperty(input.propertyName);
    }
    if (input.action === "slots")
      return {
        slots: Object.fromEntries(
          Object.entries(componentProperties(definitionsFor(component))).filter(
            ([, definition]) => definition.type === "SLOT",
          ),
        ),
      };
    if (input.action === "slot_create") {
      if (component.type !== "COMPONENT")
        fail(
          "UNSUPPORTED_BY_BRIDGE",
          "Figma createSlot is available on ComponentNode, not ComponentSetNode. Target a concrete component.",
        );
      if (
        Object.keys(definitionsFor(component)).some(
          (key) =>
            key === input.slotName || key.split("#")[0] === input.slotName,
        )
      )
        fail("INVALID_ARGUMENT", "Component property already exists.");
      const definitionsBefore = new Set(Object.keys(definitionsFor(component)));
      const slot = component.createSlot();
      try {
        const createdDefinitionKeys = Object.entries(definitionsFor(component))
          .filter(
            ([key, definition]) =>
              !definitionsBefore.has(key) && definition.type === "SLOT",
          )
          .map(([key]) => key);
        const initialKey =
          slot.componentPropertyReferences?.slot ??
          (createdDefinitionKeys.length === 1
            ? createdDefinitionKeys[0]
            : undefined);
        if (!initialKey)
          fail(
            "INTERNAL_ERROR",
            "Figma created a SlotNode without a slot property reference.",
          );
        slot.name = input.slotName;
        const currentDefinitionKeys = Object.entries(definitionsFor(component))
          .filter(
            ([key, definition]) =>
              !definitionsBefore.has(key) && definition.type === "SLOT",
          )
          .map(([key]) => key);
        const currentKey =
          currentDefinitionKeys.length === 1
            ? currentDefinitionKeys[0]
            : definitionsFor(component)[initialKey]
              ? initialKey
              : undefined;
        if (!currentKey)
          fail(
            "INTERNAL_ERROR",
            "Figma renamed the SlotNode without exposing its current property key.",
          );
        const propertyKey = component.editComponentProperty(currentKey, {
          ...(input.allowedComponentKeys
            ? {
                preferredValues: input.allowedComponentKeys.map((key) => ({
                  type: "COMPONENT",
                  key,
                })),
              }
            : {}),
          ...(input.description !== undefined
            ? { description: input.description }
            : {}),
          ...(input.slotSettings ? { slotSettings: input.slotSettings } : {}),
        });
        recordChange("component.slot_create", [component.id, slot.id]);
        return {
          component: componentRecord(component),
          node: await serializeNode(component, true),
          slot: await serializeNode(slot, true),
          propertyKey,
        };
      } catch (error) {
        let createdKeys = [];
        try {
          createdKeys = Object.entries(definitionsFor(component))
            .filter(
              ([key, definition]) =>
                !definitionsBefore.has(key) && definition.type === "SLOT",
            )
            .map(([key]) => key);
        } catch {}
        if (slot.parent) slot.remove();
        for (const key of createdKeys) {
          try {
            if (definitionsFor(component)[key])
              component.deleteComponentProperty(key);
          } catch {}
        }
        throw error;
      }
    }
    recordChange(`component.${input.action}`, [component.id]);
    return {
      component: componentRecord(component),
      node: await serializeNode(component),
    };
  }

  async function resolveComponent(input) {
    if (input.componentId) {
      const node = await nodeById(input.componentId);
      if (node.type !== "COMPONENT")
        fail("INVALID_ARGUMENT", "Target is not a component.");
      return node;
    }
    if (input.componentKey) {
      const components = await localComponents();
      const local = components.find(
        (component) =>
          component.type === "COMPONENT" &&
          component.key === input.componentKey,
      );
      if (local) return local;
      return importPublishedComponent(input.componentKey, "COMPONENT");
    }
    fail("INVALID_ARGUMENT", "componentId or componentKey is required.");
  }
  return { command: componentCommand, resolveComponent };
}

// Source: plugin/domains/instance.js
function createInstanceDomain({
  fail,
  assertNodeIds,
  recordChange,
  nodeById,
  hasChildren,
  serializeNode,
  resolveComponent,
}) {
  function slotIn(node, slotName) {
    if (
      node.type === "SLOT" &&
      (node.name === slotName ||
        node.componentPropertyReferences?.slot === slotName ||
        node.componentPropertyReferences?.slot?.split("#")[0] === slotName)
    )
      return node;
    if (!hasChildren(node)) return undefined;
    for (const child of node.children) {
      const found = slotIn(child, slotName);
      if (found) return found;
    }
    return undefined;
  }

  async function requireInstances(ids) {
    assertNodeIds(ids);
    return Promise.all(
      ids.map(async (id) => {
        const node = await nodeById(id);
        if (node.type !== "INSTANCE")
          fail("INVALID_ARGUMENT", "Every target must be an instance.");
        return node;
      }),
    );
  }

  function propertyValues(instance) {
    return Object.fromEntries(
      Object.entries(instance.componentProperties || {}).flatMap(
        ([key, value]) => (value.type === "SLOT" ? [] : [[key, value.value]]),
      ),
    );
  }

  function resolvePropertyPatch(instance, properties) {
    const available = Object.keys(instance.componentProperties || {});
    return Object.fromEntries(
      Object.entries(properties).map(([requested, value]) => {
        let resolved = requested;
        if (!available.includes(requested)) {
          const matches = available.filter(
            (key) => key.split("#")[0] === requested,
          );
          if (matches.length !== 1)
            fail(
              "INVALID_ARGUMENT",
              matches.length
                ? `Component property name ${requested} is ambiguous.`
                : `Component property ${requested} does not exist on instance ${instance.id}.`,
              false,
              {
                requested,
                matches,
                available: available.map((key) => ({
                  key,
                  name: key.split("#")[0],
                })),
              },
            );
          resolved = matches[0];
        }
        if (instance.componentProperties?.[resolved]?.type === "SLOT")
          fail(
            "INVALID_ARGUMENT",
            `Component property ${requested} is a SLOT; use slot_append or slot_reset.`,
          );
        return [resolved, value];
      }),
    );
  }

  async function defaultPropertyValues(instance) {
    const main = await instance.getMainComponentAsync();
    let definitions = {};
    try {
      definitions = main?.componentPropertyDefinitions || {};
    } catch {
      if (main?.parent?.type === "COMPONENT_SET")
        definitions = main.parent.componentPropertyDefinitions || {};
    }
    const current = Object.keys(instance.componentProperties || {});
    return Object.fromEntries(
      current.flatMap((key) => {
        let definition = definitions[key];
        if (!definition) {
          const matches = Object.entries(definitions).filter(
            ([candidate]) => candidate.split("#")[0] === key.split("#")[0],
          );
          if (matches.length > 1)
            fail(
              "INVALID_ARGUMENT",
              `Component property default for ${key} is ambiguous.`,
              false,
              { key, matches: matches.map(([candidate]) => candidate) },
            );
          definition = matches[0]?.[1];
        }
        return definition &&
          definition.type !== "SLOT" &&
          definition.defaultValue !== undefined
          ? [[key, definition.defaultValue]]
          : [];
      }),
    );
  }

  async function serializeInstances(instances) {
    return Promise.all(instances.map((node) => serializeNode(node, true)));
  }

  async function instanceCommand(input) {
    if (input.action === "inspect") {
      const instances = await requireInstances(input.instanceIds);
      return { instances: await serializeInstances(instances) };
    }
    if (input.dryRun) return { dryRun: true, action: input.action };
    if (input.action === "create") {
      const component = await resolveComponent(input);
      const parent = await nodeById(input.parentId);
      if (!hasChildren(parent))
        fail("INVALID_ARGUMENT", "Instance parent cannot contain children.");
      const instance = component.createInstance();
      try {
        const properties = input.properties
          ? resolvePropertyPatch(instance, input.properties)
          : undefined;
        parent.appendChild(instance);
        if (input.x !== undefined) instance.x = input.x;
        if (input.y !== undefined) instance.y = input.y;
        if (properties) instance.setProperties(properties);
      } catch (error) {
        if (instance.parent) instance.remove();
        throw error;
      }
      recordChange("instance.create", [instance.id]);
      return { instances: [await serializeNode(instance, true)] };
    }

    if (input.action === "slot_append" || input.action === "slot_reset") {
      const [instance] = await requireInstances([input.instanceId]);
      const slot = slotIn(instance, input.slotName);
      if (!slot)
        fail(
          "SLOT_NOT_FOUND",
          `Instance ${instance.id} has no SLOT named ${input.slotName}.`,
        );
      if (input.action === "slot_append") {
        const component = await resolveComponent({
          componentKey: input.componentKey,
        });
        const appended = component.createInstance();
        try {
          slot.appendChild(appended);
        } catch (error) {
          if (appended.parent) appended.remove();
          throw error;
        }
      } else {
        try {
          slot.resetSlot();
        } catch {
          fail(
            "UNKNOWN_OUTCOME",
            "Slot reset failed after dispatch; removed slot children cannot be reconstructed safely.",
            false,
            { instanceId: instance.id, slotId: slot.id },
          );
        }
      }
      recordChange(`instance.${input.action}`, [instance.id, slot.id]);
      return {
        instances: [await serializeNode(instance, true)],
        slot: {
          id: slot.id,
          type: slot.type,
          name: slot.name,
          childCount: slot.children.length,
          limitViolations: [...(slot.limitViolations || [])],
        },
      };
    }

    const instances = await requireInstances(input.instanceIds);
    if (input.action === "swap") {
      const component = await resolveComponent(input);
      let completedCount = 0;
      try {
        for (const instance of instances) {
          if (input.preserveOverrides === false)
            instance.mainComponent = component;
          else instance.swapComponent(component);
          completedCount += 1;
        }
      } catch {
        fail(
          "UNKNOWN_OUTCOME",
          "Instance swap failed after dispatch; visual and nested overrides cannot be rolled back safely.",
          false,
          {
            completedCount,
            attemptedIndex: completedCount,
            total: instances.length,
          },
        );
      }
    } else if (input.action === "update") {
      const patches = instances.map((instance) =>
        resolvePropertyPatch(instance, input.properties),
      );
      const snapshots = instances.map((instance) => ({
        instance,
        properties: propertyValues(instance),
      }));
      try {
        for (const [index, instance] of instances.entries())
          instance.setProperties(patches[index]);
      } catch (error) {
        try {
          for (const snapshot of snapshots)
            snapshot.instance.setProperties(snapshot.properties);
        } catch {
          fail(
            "UNKNOWN_OUTCOME",
            "Instance property update failed and rollback was incomplete.",
          );
        }
        throw error;
      }
    } else if (input.action === "reset") {
      const defaults = await Promise.all(instances.map(defaultPropertyValues));
      let completedCount = 0;
      try {
        for (const [index, instance] of instances.entries()) {
          if (typeof instance.removeOverrides === "function")
            instance.removeOverrides();
          else instance.resetOverrides();
          instance.setProperties(defaults[index]);
          completedCount += 1;
        }
      } catch {
        fail(
          "UNKNOWN_OUTCOME",
          "Instance reset failed after dispatch; removed visual and nested overrides cannot be reconstructed safely.",
          false,
          {
            completedCount,
            attemptedIndex: completedCount,
            total: instances.length,
          },
        );
      }
    }
    recordChange(`instance.${input.action}`, input.instanceIds);
    return { instances: await serializeInstances(instances) };
  }
  return { command: instanceCommand };
}

// Source: plugin/domains/tokens.js
function createTokensDomain({
  figma,
  fail,
  revisionCached,
  countSceneTraversal,
  recordChange,
  nodeById,
}) {
  async function tokensCommand(input) {
    if (input.action === "inspect") {
      return revisionCached("tokens.inventory", async () => {
        const collections =
          await figma.variables.getLocalVariableCollectionsAsync();
        const variables = await figma.variables.getLocalVariablesAsync();
        countSceneTraversal(collections.length + variables.length);
        return {
          collections: collections.map((item) => ({
            id: item.id,
            name: item.name,
            defaultModeId: item.defaultModeId,
            modes: item.modes,
          })),
          variables: variables.map((item) => ({
            id: item.id,
            key: item.key,
            name: item.name,
            resolvedType: item.resolvedType,
            collectionId: item.variableCollectionId,
            valuesByMode: item.valuesByMode,
          })),
        };
      });
    }
    if (input.dryRun)
      return {
        dryRun: true,
        action: input.action,
        operations: input.operations || [],
      };
    if (input.action === "collection_create") {
      const collection = figma.variables.createVariableCollection(input.name);
      if (input.initialModeName)
        collection.renameMode(collection.defaultModeId, input.initialModeName);
      recordChange("tokens.collection_create", [collection.id]);
      return {
        collection: {
          id: collection.id,
          name: collection.name,
          defaultModeId: collection.defaultModeId,
          modes: collection.modes,
        },
      };
    }
    if (input.action === "collection_delete") {
      const collection = await figma.variables.getVariableCollectionByIdAsync(
        input.collectionId,
      );
      if (!collection)
        fail(
          "NODE_NOT_FOUND",
          `Variable collection ${input.collectionId} was not found.`,
        );
      collection.remove();
      recordChange("tokens.collection_delete", [input.collectionId]);
      return { deletedCollectionId: input.collectionId };
    }
    for (const operation of input.operations) {
      if (operation.op === "bind") {
        const variable = await figma.variables.getVariableByIdAsync(
          operation.variableId,
        );
        if (!variable)
          fail(
            "NODE_NOT_FOUND",
            `Variable ${operation.variableId} was not found.`,
          );
        for (const id of operation.nodeIds) {
          const node = await nodeById(id);
          if (node.type === "DOCUMENT" || node.type === "PAGE")
            fail("INVALID_ARGUMENT", `Node ${id} cannot bind variables.`);
          node.setBoundVariable(operation.field, variable);
        }
      }
      if (operation.op === "set_value" || operation.op === "alias") {
        const variable = await figma.variables.getVariableByIdAsync(
          operation.variableId,
        );
        if (!variable)
          fail(
            "NODE_NOT_FOUND",
            `Variable ${operation.variableId} was not found.`,
          );
        const value =
          operation.op === "alias"
            ? figma.variables.createVariableAlias(
                await figma.variables.getVariableByIdAsync(
                  operation.targetVariableId,
                ),
              )
            : operation.value;
        variable.setValueForMode(operation.modeId, value);
      }
      if (operation.op === "mode_add" || operation.op === "mode_rename") {
        const collection = await figma.variables.getVariableCollectionByIdAsync(
          operation.collectionId,
        );
        if (!collection)
          fail(
            "NODE_NOT_FOUND",
            `Variable collection ${operation.collectionId} was not found.`,
          );
        if (operation.op === "mode_add") collection.addMode(operation.name);
        else collection.renameMode(operation.modeId, operation.name);
      }
    }
    recordChange("tokens.apply", []);
    return tokensCommand({ action: "inspect" });
  }
  return { command: tokensCommand };
}

// Source: plugin/src/main.js
figma.showUI(__html__, { width: 360, height: 300, themeColors: true });

const dataHelpers = createPluginDataHelpers();
const errors = createPluginErrors();
const metrics = createPluginMetrics();
const revision = createPluginRevisionRuntime(dataHelpers);
const fileIdentity = createPluginIdentity({ figma, revision });
const idempotency = createPluginIdempotency({ ...dataHelpers, ...errors });
const nodeHelpers = createPluginNodeHelpers({
  figma,
  fail: errors.fail,
  countSceneTraversal: metrics.countSceneTraversal,
});
const coreNode = createCoreNodeDomain({
  figma,
  ...errors,
  ...dataHelpers,
  revisionCached: revision.revisionCached,
  recordChange: revision.recordChange,
  getChanges: revision.getChanges,
  countSceneTraversal: metrics.countSceneTraversal,
  ...nodeHelpers,
});
const layout = createLayoutDomain({
  ...errors,
  cloneData: dataHelpers.cloneData,
  countSceneTraversal: metrics.countSceneTraversal,
  recordChange: revision.recordChange,
  ...nodeHelpers,
});
const component = createComponentDomain({
  figma,
  fail: errors.fail,
  revisionCached: revision.revisionCached,
  countSceneTraversal: metrics.countSceneTraversal,
  recordChange: revision.recordChange,
  ...nodeHelpers,
});
const instance = createInstanceDomain({
  ...errors,
  recordChange: revision.recordChange,
  ...nodeHelpers,
  resolveComponent: component.resolveComponent,
});
const tokens = createTokensDomain({
  figma,
  fail: errors.fail,
  revisionCached: revision.revisionCached,
  countSceneTraversal: metrics.countSceneTraversal,
  recordChange: revision.recordChange,
  nodeById: nodeHelpers.nodeById,
});

const BRIDGE_CONFIG_KEY = "mcp-fig.bridge-config.v1";
const BRIDGE_PROTOCOL = "mcp-fig-plugin/v1";

function validBridgeConfig(value) {
  return (
    value &&
    typeof value === "object" &&
    value.version === 1 &&
    value.protocol === BRIDGE_PROTOCOL &&
    Number.isInteger(value.port) &&
    value.port >= 1 &&
    value.port <= 65535 &&
    typeof value.credential === "string" &&
    value.credential.length >= 32 &&
    value.credential.length <= 512
  );
}

async function handleBridgeConfigMessage(message) {
  const operation = message.type.slice("bridge-config-".length);
  const response = {
    type: "bridge-config-result",
    requestId:
      typeof message.requestId === "string" ? message.requestId : "invalid",
    operation,
  };
  try {
    if (operation === "get") {
      const stored = await figma.clientStorage.getAsync(BRIDGE_CONFIG_KEY);
      figma.ui.postMessage({
        ...response,
        ok: true,
        config: validBridgeConfig(stored) ? stored : null,
      });
      return;
    }
    if (operation === "set") {
      if (!validBridgeConfig(message.config)) {
        figma.ui.postMessage({
          ...response,
          ok: false,
          error: {
            code: "INVALID_CONFIG",
            message: "Bridge config is invalid.",
          },
        });
        return;
      }
      await figma.clientStorage.setAsync(BRIDGE_CONFIG_KEY, message.config);
      figma.ui.postMessage({ ...response, ok: true });
      return;
    }
    if (operation === "clear") {
      await figma.clientStorage.deleteAsync(BRIDGE_CONFIG_KEY);
      figma.ui.postMessage({ ...response, ok: true });
    }
  } catch {
    figma.ui.postMessage({
      ...response,
      ok: false,
      error: {
        code: "STORAGE_ERROR",
        message: "Figma could not access the saved bridge config.",
      },
    });
  }
}

async function execute(command) {
  const identity = fileIdentity();
  if (command.fileKey !== identity.key) {
    errors.fail(
      "FILE_NOT_TARGETED",
      `Command targets ${command.fileKey}, but this plugin owns ${identity.key}.`,
      true,
    );
  }
  const prepared = idempotency.prepare(identity.key, command);
  if (prepared?.replayed) return prepared.data;
  if (
    command.expectedRevision &&
    command.expectedRevision !== identity.revision
  ) {
    errors.fail(
      "REVISION_CONFLICT",
      `Expected revision ${command.expectedRevision}, but file ${identity.key} is at ${identity.revision}.`,
      true,
      {
        fileKey: identity.key,
        expectedRevision: command.expectedRevision,
        actualRevision: identity.revision,
        targetNodeIds: command.targetNodeIds || [],
      },
    );
  }

  let result;
  if (
    command.method.startsWith("document.") ||
    ["selection.get", "changes.get"].includes(command.method) ||
    command.method.startsWith("node.")
  ) {
    result = await coreNode.command(command.method, command.params || {});
  } else if (command.method === "layout") {
    result = await layout.command(command.params || {});
  } else if (command.method === "component") {
    result = await component.command(command.params || {});
  } else if (command.method === "instance") {
    result = await instance.command(command.params || {});
  } else if (command.method === "tokens") {
    result = await tokens.command(command.params || {});
  } else {
    errors.fail(
      "UNSUPPORTED_BY_BRIDGE",
      `Unknown Desktop Plugin method ${command.method}.`,
    );
  }
  idempotency.store(prepared, result);
  return result;
}

figma.ui.onmessage = async (message) => {
  if (
    message?.type === "bridge-config-get" ||
    message?.type === "bridge-config-set" ||
    message?.type === "bridge-config-clear"
  ) {
    await handleBridgeConfigMessage(message);
    return;
  }
  if (message?.type === "bridge-bootstrap") {
    figma.ui.postMessage({ type: "bridge-bootstrap", file: fileIdentity() });
    return;
  }
  if (message?.type !== "bridge-command" || !message.command) return;
  const requestId = message.command.requestId;
  const traceId = message.command.traceId || requestId;
  metrics.start();
  const figmaApiStartedAt = new Date().toISOString();
  try {
    const data = await execute(message.command);
    const figmaApiCompletedAt = new Date().toISOString();
    figma.ui.postMessage({
      type: "bridge-result",
      requestId,
      traceId,
      ok: true,
      data,
      revision: String(revision.current()),
      figmaApiStartedAt,
      figmaApiCompletedAt,
      sceneTraversalNodeCount: metrics.sceneTraversalNodeCount(),
    });
  } catch (error) {
    const figmaApiCompletedAt = new Date().toISOString();
    const bridge = error?.bridge || {
      code: "INTERNAL_ERROR",
      message: error instanceof Error ? error.message : String(error),
      retryable: false,
    };
    figma.ui.postMessage({
      type: "bridge-result",
      requestId,
      traceId,
      ok: false,
      error: bridge,
      revision: String(revision.current()),
      figmaApiStartedAt,
      figmaApiCompletedAt,
      sceneTraversalNodeCount: metrics.sceneTraversalNodeCount(),
    });
  } finally {
    metrics.finish();
  }
};

figma.ui.postMessage({ type: "bridge-bootstrap", file: fileIdentity() });

figma.on("selectionchange", () => {
  figma.ui.postMessage({ type: "bridge-bootstrap", file: fileIdentity() });
});

async function initializeDocumentChangeTracking() {
  await figma.loadAllPagesAsync();
  figma.on("documentchange", (event) => {
    revision.recordExternalChange(event);
    figma.ui.postMessage({ type: "bridge-bootstrap", file: fileIdentity() });
  });
}

void initializeDocumentChangeTracking();
