import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sources = [
  "plugin/shared/data.js",
  "plugin/runtime/errors.js",
  "plugin/runtime/metrics.js",
  "plugin/runtime/revision.js",
  "plugin/runtime/identity.js",
  "plugin/runtime/idempotency.js",
  "plugin/shared/node.js",
  "plugin/domains/core-node.js",
  "plugin/domains/layout.js",
  "plugin/domains/component.js",
  "plugin/domains/instance.js",
  "plugin/domains/tokens.js",
  "plugin/src/main.js",
];
const outputPath = path.join(root, "plugin/main.js");

const parts = await Promise.all(
  sources.map(async (source) => {
    const content = await readFile(path.join(root, source), "utf8");
    const assembled = content.replace(
      /^\/\/ biome-ignore lint\/correctness\/noUnusedVariables: Used by the deterministic plugin assembly\.\n/,
      "",
    );
    return `// Source: ${source}\n${assembled.trim()}\n`;
  }),
);
const output = `// Generated by scripts/build-plugin.mjs. Do not edit directly.\n// Figma loads this single sandbox artifact through plugin/manifest.json.\n\n${parts.join("\n")}`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== output) {
    console.error("plugin/main.js is stale; run npm run build:plugin.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, output);
  console.log(`Built plugin/main.js from ${sources.length} ordered modules.`);
}
